=== vinv-group/vinv-schema/0.1-alpha/vinv.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/vinv-group/vinv-schema/alpha/0.1-alpha/vinv.json",
    "title": "vinv schema",
    "description": "Lightweight data standard for individual tree based forest management, visualisation & analytics",
    "type": "object",
    "additionalProperties": false,
    "properties":{
        "$schema": {
            "type": "string",
            "examples": [
                "https://raw.githubusercontent.com/vinv-group/vinv-schema/main/0.1-alpha/vinv.json"
            ]
        },
        "v": {
            "title": "Version of the used vinv schema, the file should be validated against",
            "type": "string",
            "pattern": "^[0-9]\\.[0-9](-alpha|-beta|-stable)?$",
            "examples": [
                "0.1",
                "0.1-beta"
            ]
        },
        "trees": {
            "type": ["array", "null"],
            "minItems":1,
            "maxItems": 2,
            "items": [
                {
                    "type": "object",
                    "propertyNames": {
                        "pattern": "^[A-Za-z0-9_-]*$"
                    },
                    "additionalProperties": {"$ref": "./definitions/tree.json"}
                },
                {
                    "type":["array", "null"],
                    "items": {"$ref": "./definitions/changes/tree_history.json"}
                }
            ]
        },
        "roads":{
            "type": ["array", "null"],
            "minItems":1,
            "maxItems": 2,
            "items": [
                {
                    "type": "object",
                    "propertyNames": {
                        "pattern": "^[A-Za-z0-9_-]*$"
                    },
                    "items": {"$ref": "./definitions/track.json"}
                },
                {
                    "type":["array", "null"],
                    "items": {"$ref": "./definitions/changes/track_history.json"}
                }
            ]
        },
        "area":{
            "type": ["array", "null"],
            "minItems":1,
            "maxItems": 2,
            "items": [
                {
                    "type": "object",
                    "propertyNames": {
                        "pattern": "^[A-Za-z0-9_-]*$"
                    },
                    "additionalProperties": {"$ref": "./definitions/area.json"}
                },
                {
                    "type":["array", "null"],
                    "additionalItems": false,
                    "items": {"$ref": "./definitions/changes/area_history.json"}
                }
            ]
        },
        "fallbacks":{
            "type":"array",
            "additionalItems": false,
            "items": {"$ref": "./definitions/fallbacks.json"}
        }
    },
    "required": [
        "v"
    ]
}

=== vinv-group/vinv-schema/0.1-alpha/examples/random.json
{
    "$schema": "../vinv.json",
    "v": "0.1-alpha",
    "trees": [
        {
            "fddd":[
                [[23.56,23.222], 12],
                "34_",
                23,12, 
                [[0.5,5], [0.3,5]],
                "2018-11-13",
                {"obj": "https://www.der.de"}
            ],
            "sdfsdfs":[
                [[23.56,23.222, 0], 12],
                "34_",
                23,
                12, 
                [[0.3,5], [0.6,5]],
                "2018-11-13",
                {"obj": "https://www.der.de"}
            ]
        }
    ],
    "roads": [
        {
            "sdfsdfd":[
                [
                    [
                        [23.56,23.222]
                    ],
                    [
                        [23.56,23.222, 0],
                        49.83
                    ],
                    [
                        [23.56,23.222, 0],
                        40.44
                    ],
                    [
                        [23.56,23.222, 0],
                        36.59
                    ],
                    [
                        [23.56,23.222, 0],
                        32.24
                    ]
                ],
                "dsfsdf"
            ]
        }
    ],
    "area": [
        {
            "sdfsdfd":[
                [
                    [
                        [
                            [23.56,23.222]
                        ],
                        [
                            [23.56,23.222, 0],
                            23
                        ],
                        [
                            [23.56,23.222, 0],
                            40.44
                        ],
                        [
                            [23.56,23.222, 0],
                            36.59
                        ],
                        [
                            [23.56,23.222, 0],
                            32.24
                        ]
                    ]
                ],
                "dsfsdf"
            ]
        }
    ],
    "fallbacks": [
        [
            [
                ["sf6", "9hD"],
                [0,100]
            ],
            [
                [[23.56,23.222], 12],
                "34_",
                23, 12,
                [[0.2,5], [0.1,5]],
                "2018-11-13",
                {"obj": "https://www.der.de"}
            ]
        ]
    ]
}
