=== vinv-group/vinv-schema/docs/vinv-roundwood-pile/en/0.0.2-beta.json
{"$schema":"http://json-schema.org/draft-07/schema#","title":"RoundwoodPile","description":"Roundwood Pile","type":"object","required":["location","logs"],"properties":{"location":{"$ref":"https://schema.vinv.io/location/en/0.0.2-beta.json"},"logs":{"title":"Logs","description":"Multiple logs definition.","type":"array","minItems":1,"items":{"$ref":"https://schema.vinv.io/log/en/0.0.2-beta.json"}},"image_pile_front":{"title":"Image","description":"Image of the Pile front","$ref":"https://schema.vinv.io/image/en/0.0.2-beta.json"},"treeNumber":{"title":"Unique number","description":"Number/ID of the tree","type":"string","maxLength":26,"examples":["#1","45","ASDF435gHDFGhsgj5646"]}},"$id":"https://schema.vinv.io/vinv-roundwood-pile/en/0.0.2-beta.json"}

=== vinv-group/vinv-schema/docs/vinv-roundwood-pile/en/0.0.2-beta/example.json
{
  "location": {
    "coordinates": {
      "longitude": 130.5627874,
      "latitude": 50.5627874,
      "altitude": 130
    },
    "accuracy": 12,
    "geogrid": {
      "h3": "8428309ffffffff",
      "geohash": "ww8p1r4t8"
    }
  },
  "logs": [
    {
      "species": "JM2",
      "dimensions": [
        {
          "height": 0.1,
          "diameter": 38
        },
        {
          "height": 0.1,
          "diameter": 38
        },
        {
          "height": 0.1,
          "diameter": 38
        }
      ],
      "image_log": {
        "uri": "https://schema.vinv.io/asset/img/logo.png",
        "encoder": "image/jpeg",
        "compression": 0.8,
        "width": 500,
        "height": 500
      },
      "treeNumber": "ASDF435gHDFGhsgj5646"
    },
    {
      "species": "JM2",
      "dimensions": [
        {
          "height": 0.1,
          "diameter": 38
        },
        {
          "height": 0.1,
          "diameter": 38
        },
        {
          "height": 0.1,
          "diameter": 38
        }
      ],
      "image_log": {
        "uri": "https://schema.vinv.io/asset/img/logo.png",
        "encoder": "image/jpeg",
        "compression": 0.8,
        "width": 500,
        "height": 500
      },
      "treeNumber": "ASDF435gHDFGhsgj5646"
    },
    {
      "species": "JM2",
      "dimensions": [
        {
          "height": 0.1,
          "diameter": 38
        },
        {
          "height": 0.1,
          "diameter": 38
        },
        {
          "height": 0.1,
          "diameter": 38
        }
      ],
      "image_log": {
        "uri": "https://schema.vinv.io/asset/img/logo.png",
        "encoder": "image/jpeg",
        "compression": 0.8,
        "width": 500,
        "height": 500
      },
      "treeNumber": "ASDF435gHDFGhsgj5646"
    }
  ],
  "image_pile_front": {
    "uri": "https://schema.vinv.io/asset/img/logo.png",
    "encoder": "image/jpeg",
    "compression": 0.8,
    "width": 500,
    "height": 500
  },
  "treeNumber": "ASDF435gHDFGhsgj5646",
  "$schema": "https://schema.vinv.io/vinv-roundwood-pile/en/0.0.2-beta.json"
}
