=== vinv-group/vinv-schema/docs/log/en/0.0.2-beta.json
{"$id":"https://schema.vinv.io/log/0.0.2-beta.json","$schema":"http://json-schema.org/draft-07/schema#","title":"Log","description":"A part of the trunk or a large branch of a tree that has fallen or been cut off.","type":"object","required":["species","dimensions"],"properties":{"species":{"$ref":"https://schema.vinv.io/species/0.0.1.json"},"dimensions":{"title":"Dimensions","description":"Dimensions of the log","type":"array","minItems":1,"items":{"$ref":"https://schema.vinv.io/diameter_at_height/0.0.1.json"}},"image_log":{"title":"Image","description":"Image of the log","$ref":"https://schema.vinv.io/image/0.0.1.json"},"treeNumber":{"title":"Unique number","description":"Number/ID of the tree","type":"string","maxLength":26,"examples":["#1","45","ASDF435gHDFGhsgj5646"]}}}

=== vinv-group/vinv-schema/docs/log/en/0.0.2-beta/example.json
{
  "species": "JM2",
  "dimensions": [
    {
      "height": 0.1,
      "diameter": 38
    },
    {
      "height": 0.1,
      "diameter": 38
    },
    {
      "height": 0.1,
      "diameter": 38
    }
  ],
  "image_log": {
    "uri": "https://schema.vinv.io/asset/img/logo.png",
    "encoder": "image/jpeg",
    "compression": 0.8,
    "width": 500,
    "height": 500
  },
  "treeNumber": "ASDF435gHDFGhsgj5646",
  "$schema": "https://schema.vinv.io/log/0.0.2-beta.json"
}
