=== vinv-group/vinv-schema/0.1-alpha/dist/vinv.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://schema.vinv.io/0.1-alpha/dist/vinv.json",
  "title": "vinv",
  "description": "Lightweight data standard for individual tree based forest management, visualisation & analytics",
  "type": "object",
  "additionalProperties": false,
  "definitions": {
    "tree": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Tree definition",
      "description": "",
      "type": "array",
      "minItems": 4,
      "maxItems": 8,
      "items": [
        {
          "$ref": "#/definitions/location"
        },
        {
          "$ref": "#/definitions/species"
        },
        {
          "title": "Diameter at Breast Height",
          "description": "Diameter in centimeter",
          "type": [
            "number",
            "null"
          ],
          "minimum": 1,
          "maximum": 100,
          "multipleOf": 1
        },
        {
          "title": "Height",
          "description": "Height in centimeter",
          "type": [
            "number",
            "null"
          ],
          "minimum": 10,
          "maximum": 1000,
          "multipleOf": 1
        },
        {
          "title": "Trunk definition",
          "description": "Diameter per height",
          "type": [
            "array",
            "null"
          ],
          "$ref": "#/definitions/dimensions_trunk"
        },
        {
          "title": "Crown definition",
          "description": "Diameter per height",
          "type": [
            "array",
            "null"
          ],
          "$ref": "#/definitions/dimensions_crown"
        },
        {
          "title": "birth",
          "description": "Birthday of the tree",
          "examples": [
            "2018-11-13"
          ],
          "type": [
            "string",
            "null"
          ],
          "format": "date"
        },
        {
          "title": "Images",
          "description": "List of absolute or relative path to file",
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/image"
          }
        }
      ]
    },
    "trees_history": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Tree Changes",
      "description": "Changes to the tree data",
      "type": "array",
      "minItems": 3,
      "maxItems": 3,
      "items": [
        {
          "title": "Tree Id",
          "description": "URL-friendly id",
          "type": "string",
          "pattern": "^[A-Za-z0-9_-]*$",
          "maxLength": 36
        },
        {
          "title": "Time of Change",
          "description": "Date and time when change happened.",
          "examples": [
            "2018-11-13T20:20:39+00:00"
          ],
          "type": "string",
          "format": "date-time"
        },
        {
          "title": "Tree data change",
          "description": "Tree state before manipulation.",
          "$ref": "#/definitions/tree"
        }
      ]
    },
    "track": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Track definition",
      "description": "",
      "type": "array",
      "minItems": 1,
      "maxItems": 2,
      "additionalItem": false,
      "items": [
        {
          "title": "LineString coordinates",
          "minItems": 2,
          "type": "array",
          "items": [
            {
              "$ref": "#/definitions/location"
            }
          ],
          "additionalItems": {
            "$ref": "#/definitions/location"
          }
        },
        {
          "title": "Width",
          "description": "Width of the track in METER",
          "type": "number",
          "minimum": 0.1,
          "maximum": 10
        }
      ]
    },
    "track_history": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Track Changes",
      "description": "Changes to the track data",
      "type": "array",
      "minItems": 3,
      "maxItems": 3,
      "items": [
        {
          "title": "Track Id",
          "description": "URL-friendly id",
          "type": "string",
          "pattern": "^[A-Za-z0-9_-]*$",
          "maxLength": 36
        },
        {
          "title": "Change",
          "description": "Date and time when change happened.",
          "examples": [
            "2018-11-13T20:20:39+00:00"
          ],
          "type": "string",
          "format": "date-time"
        },
        {
          "title": "Track data change",
          "description": "Tree state before manipulation.",
          "$ref": "#/definitions/track"
        }
      ]
    },
    "area": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Area definition",
      "description": "",
      "type": "array",
      "minItems": 1,
      "additionalItem": false,
      "items": [
        {
          "type": "array",
          "title": "Polygon coordinates",
          "minItems": 1,
          "items": {
            "type": "array",
            "title": "Polygon coordinates",
            "items": {
              "$ref": "#/definitions/location"
            },
            "minItems": 3
          }
        }
      ]
    },
    "area_history": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Area Changes",
      "description": "Changes to the track data",
      "type": "array",
      "minItems": 3,
      "maxItems": 3,
      "items": [
        {
          "title": "Track Id",
          "description": "URL-friendly id",
          "type": "string",
          "pattern": "^[A-Za-z0-9_-]*$",
          "maxLength": 36
        },
        {
          "title": "Change",
          "description": "Date and time when change happened.",
          "examples": [
            "2018-11-13T20:20:39+00:00"
          ],
          "type": "string",
          "format": "date-time"
        },
        {
          "title": "Track data change",
          "description": "Tree state before manipulation.",
          "$ref": "#/definitions/area"
        }
      ]
    },
    "location": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Location",
      "description": "",
      "type": "array",
      "minItems": 1,
      "maxItems": 2,
      "additionalItems": false,
      "items": [
        {
          "$ref": "#/definitions/coordinates"
        },
        {
          "title": "Accuracy",
          "description": "The decimal accuracy of coordinates in meter (2 decimal places max).",
          "type": [
            "number",
            "null"
          ],
          "minimum": 0
        }
      ]
    },
    "coordinates": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Coordinates",
      "description": "Anchor point of the Object on a map. Array of longitude, latitude and [altitude] coordinate. Reference system: WGS84 Web Mercator with longitude and latitude units of decimal degrees.",
      "type": "array",
      "minItems": 2,
      "maxItems": 3,
      "additionalItems": false,
      "items": [
        {
          "title": "Longitude",
          "description": "The decimal east–west position of a point. (7 decimal places max)",
          "type": "number",
          "minimum": -180,
          "maximum": 180
        },
        {
          "title": "Latitude",
          "description": "The decimal north–south position of a point. (7 decimal places max)",
          "type": "number",
          "minimum": -90,
          "maximum": 90
        },
        {
          "type": "number",
          "title": "[Altitude]",
          "description": "The altitude of the position in meters above mean sea level. (2 decimal places max)",
          "minimum": 0
        }
      ]
    },
    "dbh": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Diameter at breast height",
      "description": "Array including height and diameter",
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "items": [
        {
          "type": "number",
          "title": "Height",
          "description": "Height in meter of diameter measurment",
          "const": 1.3,
          "default": 1.3
        },
        {
          "type": "number",
          "title": "Diameter",
          "description": "Diameter in centimeter as measured height",
          "minimum": 0,
          "maximum": 100
        }
      ]
    },
    "species": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Tree species",
      "description": "Tree Species values taken from https://github.com/b-lack/tree-species",
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]{3}$",
      "examples": [
        "JM2",
        "sf6",
        "9hD",
        "u2-"
      ]
    },
    "dimensions_trunk": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Additional trunk measurements",
      "type": [
        "array",
        "null"
      ],
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/diameter_height"
      }
    },
    "dimensions_crown": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Additional crown measurements",
      "type": [
        "array",
        "null"
      ],
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/diameter_height"
      }
    },
    "diameter_height": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Diameter at height",
      "description": "Array including height and diameter at height",
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "additionalItems": false,
      "items": [
        {
          "type": "number",
          "title": "Height",
          "description": "Height of tree in PERCENT where diameter is measured",
          "minimum": 0.1,
          "maximum": 1,
          "examples": [
            0.5,
            0.1
          ]
        },
        {
          "type": "number",
          "title": "Diameter",
          "description": "Diameter in CENTIMETER at measured height",
          "minimum": 0.1,
          "maximum": 100
        }
      ]
    },
    "filter": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Filter definition",
      "type": "array",
      "items": [
        {
          "title": "Location radius",
          "type": [
            "array",
            "null"
          ],
          "minItems": 2,
          "maxItems": 2,
          "uniqueItems": true,
          "items": [
            {
              "$ref": "#/definitions/coordinates"
            },
            {
              "title": "Radius",
              "description": "Radius in Meter.",
              "examples": [
                "56.42"
              ],
              "type": "number"
            }
          ]
        },
        {
          "title": "Tree Species",
          "description": "Array of tree species to be filtered.",
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/species"
          }
        },
        {
          "title": "DBH range",
          "description": "Define range of maximum set tree diameter.",
          "type": [
            "array",
            "null"
          ],
          "minItems": 2,
          "maxItems": 2,
          "items": [
            {
              "title": "Minimum diameter",
              "type": [
                "number",
                "null"
              ],
              "minimum": 0
            },
            {
              "title": "Maximum diameter",
              "type": [
                "number",
                "null"
              ],
              "maximum": 100
            }
          ]
        },
        {
          "title": "Height range",
          "description": "Define Range of tree height to filter",
          "type": [
            "array",
            "null"
          ],
          "minItems": 2,
          "maxItems": 2,
          "items": [
            {
              "title": "Minimum height",
              "type": [
                "number",
                "null"
              ],
              "minimum": 1,
              "multipleOf": 1
            },
            {
              "title": "Maximum height",
              "type": [
                "number",
                "null"
              ],
              "maximum": 1000,
              "multipleOf": 1
            }
          ]
        },
        {
          "title": "Birthday range",
          "description": "Define Range of tree age to filter",
          "type": [
            "array",
            "null"
          ],
          "minItems": 2,
          "maxItems": 2,
          "items": [
            {
              "title": "Minimum height",
              "description": "Minimum date of the trees birthday.",
              "examples": [
                "2018-11-13"
              ],
              "type": "string",
              "format": "date"
            },
            {
              "title": "Maximum height",
              "description": "Maximum date of the  trees birthday.",
              "examples": [
                "2018-11-13"
              ],
              "type": "string",
              "format": "date"
            }
          ]
        }
      ],
      "additionalItems": false
    },
    "image": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Images",
      "description": "A universal resource identifier (URI), according to RFC3986.",
      "type": "string",
      "pattern": "uri",
      "examples": [
        "https://via.placeholder.com/150.png",
        "https://via.placeholder.com/400x300.png",
        "https://via.placeholder.com/450x800.png"
      ]
    }
  },
  "properties": {
    "$schema": {
      "type": "string",
      "examples": [
        "https://raw.githubusercontent.com/vinv-group/vinv-schema/main/0.1-alpha/vinv.json"
      ]
    },
    "v": {
      "title": "Version",
      "description": "Version of the used vinv schema, the file should be validated against",
      "type": "string",
      "pattern": "^[0-9]\\.[0-9](-alpha|-beta|-stable)?$",
      "examples": [
        "0.1",
        "0.1-beta"
      ]
    },
    "trees": {
      "type": [
        "array",
        "null"
      ],
      "minItems": 1,
      "maxItems": 2,
      "items": [
        {
          "title": "Tree",
          "description": "Individual Tree Details",
          "type": "object",
          "propertyNames": {
            "pattern": "^[A-Za-z0-9_-]*$"
          },
          "additionalProperties": {
            "$ref": "#/definitions/tree"
          }
        },
        {
          "title": "Trees Changes",
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/trees_history"
          }
        }
      ]
    },
    "tracks": {
      "type": [
        "array",
        "null"
      ],
      "minItems": 1,
      "maxItems": 2,
      "items": [
        {
          "title": "Track",
          "description": "Track Details",
          "type": "object",
          "propertyNames": {
            "pattern": "^[A-Za-z0-9_-]*$"
          },
          "additionalProperties": {
            "$ref": "#/definitions/track"
          }
        },
        {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/track_history"
          }
        }
      ]
    },
    "areas": {
      "type": [
        "array",
        "null"
      ],
      "minItems": 1,
      "maxItems": 2,
      "items": [
        {
          "title": "Area",
          "description": "Area Details",
          "type": "object",
          "propertyNames": {
            "pattern": "^[A-Za-z0-9_-]*$"
          },
          "additionalProperties": {
            "$ref": "#/definitions/area"
          }
        },
        {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/area_history"
          }
        }
      ]
    },
    "filters": {
      "type": [
        "array",
        "null"
      ],
      "minItems": 1,
      "maxItems": 2,
      "items": {
        "$ref": "#/definitions/filter"
      }
    },
    "extensions": {
      "title": "Extensions",
      "description": "List of functional extensions",
      "type": "object",
      "propertyNames": {
        "pattern": "^[A-Za-z0-9_-]*$"
      },
      "properties": {}
    }
  },
  "required": [
    "v"
  ]
}

=== vinv-group/vinv-schema/0.1-alpha/examples/try_to_break.json
{
    "$schema": "../vinv.json",
    "v": "0.1-alpha",
    "trees": [
        {
            "fddd":[
                [[23.4444441,23.4444441], 12],
                "34_",
                23,12, 
                [[0.5,5], [0.3,5]],
                [[0.3,5], [0.6,5]],
                "2018-11-13",
                null
            ],
            "sdfsdfs":[
                [[23.4444441,23.4444441, 0], 12],
                "34_",
                23,
                12, 
                [[0.3,5], [0.6,5]],
                [[0.3,5], [0.6,5]],
                "2018-11-13",
                null
            ]
        }
    ],
    "tracks": [
        {
            "sdfsdfd":[
                [
                    [
                        [23.56,23.222]
                    ],
                    [
                        [23.56,23.222, 0],
                        49.83
                    ],
                    [
                        [23.56,23.222, 0],
                        40.44
                    ],
                    [
                        [23.56,23.222, 0],
                        36.59
                    ],
                    [
                        [23.56,23.222, 0],
                        32.24
                    ]
                ],
                5.6
            ]
        }
    ],
    "areas": [
        {
            "sdfsdfd":[
                [
                    [
                        [
                            [23.56,23.222]
                        ],
                        [
                            [23.56,23.222, 0],
                            23
                        ],
                        [
                            [23.56,23.222, 0],
                            40.44
                        ],
                        [
                            [23.56,23.222, 0],
                            36.59
                        ],
                        [
                            [23.56,23.222, 0],
                            32.24
                        ]
                    ]
                ],
                "dsfsdf"
            ]
        }
    ]
}

=== vinv-group/vinv-schema/0.1-alpha/examples/vinv-with-love.json
{
    "$schema": "../../dist/0.1-alpha.json",
    "v": "0.1-alpha",
    "trees": [
        {
            "fddd": [
                [
                    [
                        13.96727085113525,
                        47.39515368316963
                    ],
                    12
                ],
                "34_",
                23,
                12,
                [
                    [
                        0.5,
                        5
                    ],
                    [
                        0.3,
                        5
                    ]
                ],
                [
                    [
                        0.3,
                        5
                    ],
                    [
                        0.6,
                        5
                    ]
                ],
                "2018-11-13",
                null
            ],
            "sdfsdfs": [
                [
                    [
                        13.969395160675049,
                        47.39474696708006,
                        0
                    ],
                    12
                ],
                "34_",
                23,
                12,
                [
                    [
                        0.3,
                        5
                    ],
                    [
                        0.6,
                        5
                    ]
                ],
                [
                    [
                        0.3,
                        5
                    ],
                    [
                        0.6,
                        5
                    ]
                ],
                "2018-11-13",
                null
            ]
        }
    ],
    "tracks": [
        {
            "road_1": [
                [
                    [
                        [
                            34,
                            34,
                            0
                        ],
                        0
                    ],
                    [
                        [
                            34,
                            34,
                            0
                        ],
                        34
                    ]
                ],
                9.4
            ]
        },
        []
    ],
    "areas": [
        {
            "sdfsdfd": [
                [
                    [
                        [
                            [
                                23.56,
                                23.222
                            ]
                        ],
                        [
                            [
                                23.56,
                                23.222,
                                0
                            ],
                            23
                        ],
                        [
                            [
                                23.56,
                                23.222,
                                0
                            ],
                            40.44
                        ],
                        [
                            [
                                23.56,
                                23.222,
                                0
                            ],
                            36.59
                        ],
                        [
                            [
                                23.56,
                                23.222,
                                0
                            ],
                            32.24
                        ]
                    ]
                ],
                "dsfsdf"
            ]
        }
    ]
}
