=== vinv-group/vinv-schema/docs/tree/en/0.0.2-beta/dereferenced.doc.json
{
  "$id": "https://schema.vinv.io/tree/en/0.0.2-beta.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Tree",
  "description": "Tree definition",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "species",
    "trunk"
  ],
  "properties": {
    "species": {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "$vinv": {
        "id": "https://schema.vinv.io/species/en/0.0.2-beta.json",
        "enum": "https://schema.vinv.io/species/en/0.0.1.json"
      },
      "title": "Tree species",
      "description": "Tree Species values taken from https://github.com/b-lack/tree-species",
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]{3}$",
      "examples": [
        "JM2"
      ]
    },
    "trunk": {
      "type": "object",
      "title": "Trunk",
      "description": "Trunk definition",
      "required": [
        "dimensions"
      ],
      "properties": {
        "dimensions": {
          "title": "Dimensions",
          "description": "Diameter per height",
          "additionalProperties": false,
          "type": "array",
          "minItems": 2,
          "items": {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "$vinv": {
              "id": "https://schema.vinv.io/diameter_at_height/en/0.0.2-beta.json",
              "idShort": "diameter_at_height"
            },
            "additionalProperties": false,
            "title": "Diameter at height",
            "description": "Array including height and diameter at height",
            "type": "object",
            "minItems": 2,
            "maxItems": 2,
            "additionalItems": false,
            "required": [
              "height",
              "diameter"
            ],
            "properties": {
              "height": {
                "title": "Height",
                "description": "Height of measurment in METER where diameter is measured.",
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "multipleOf": 0.1,
                "examples": [
                  0.5,
                  0.1
                ],
                "$vinv": {
                  "unit": "Meter",
                  "unitSymbol": "m"
                }
              },
              "diameter": {
                "title": "Diameter",
                "description": "Diameter in CENTIMETER at measured height.",
                "type": "integer",
                "minimum": 1,
                "maximum": 5000,
                "examples": [
                  304,
                  308
                ],
                "$vinv": {
                  "unit": "Centimeter",
                  "unitSymbol": "cm"
                }
              }
            }
          }
        },
        "image_trunk": {
          "title": "Image",
          "description": "Image of the trunk",
          "$schema": "http://json-schema.org/draft-07/schema#",
          "type": [
            "object",
            "null"
          ],
          "required": [
            "uri"
          ],
          "properties": {
            "uri": {
              "title": "Image",
              "description": "A universal resource identifier (URI), according to RFC3986.",
              "type": "string",
              "format": "uri",
              "examples": [
                "https://schema.vinv.io/asset/img/logo.png"
              ]
            },
            "encoder": {
              "title": "Encoder",
              "description": "The encoder used to encode the image.",
              "type": [
                "string",
                "null"
              ],
              "default": "image/webp",
              "enum": [
                "image/jpeg",
                "image/webp"
              ],
              "examples": [
                "image/webp",
                "image/jpeg"
              ]
            },
            "compression": {
              "title": "Compression",
              "description": "The compression used to encode the image.",
              "type": [
                "number",
                "null"
              ],
              "minimum": 0,
              "maximum": 1,
              "default": 1,
              "examples": [
                0.8
              ]
            },
            "width": {
              "title": "Width",
              "description": "Width of the image.",
              "type": [
                "integer",
                "null"
              ],
              "minimum": 25,
              "maximum": 10000,
              "examples": [
                500
              ],
              "$vinv": {
                "unit": "Pixel",
                "unitSymbol": "px"
              }
            },
            "height": {
              "title": "Height",
              "description": "Height of the image",
              "type": [
                "integer",
                "null"
              ],
              "minimum": 25,
              "maximum": 10000,
              "examples": [
                500
              ],
              "$vinv": {
                "unit": "Pixel",
                "unitSymbol": "px"
              }
            }
          },
          "$vinv": {
            "id": "https://schema.vinv.io/image/en/0.0.1.json"
          }
        }
      }
    },
    "crown": {
      "type": [
        "object",
        "null"
      ],
      "title": "Crown",
      "description": "Crown definition",
      "required": [
        "dimensions"
      ],
      "properties": {
        "dimensions": {
          "title": "Dimensions",
          "description": "Diameter per height",
          "type": "array",
          "minItems": 2,
          "items": {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "$vinv": {
              "id": "https://schema.vinv.io/diameter_at_height/en/0.0.2-beta.json",
              "idShort": "diameter_at_height"
            },
            "additionalProperties": false,
            "title": "Diameter at height",
            "description": "Array including height and diameter at height",
            "type": "object",
            "minItems": 2,
            "maxItems": 2,
            "additionalItems": false,
            "required": [
              "height",
              "diameter"
            ],
            "properties": {
              "height": {
                "title": "Height",
                "description": "Height of measurment in METER where diameter is measured.",
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "multipleOf": 0.1,
                "examples": [
                  0.5,
                  0.1
                ],
                "$vinv": {
                  "unit": "Meter",
                  "unitSymbol": "m"
                }
              },
              "diameter": {
                "title": "Diameter",
                "description": "Diameter in CENTIMETER at measured height.",
                "type": "integer",
                "minimum": 1,
                "maximum": 5000,
                "examples": [
                  304,
                  308
                ],
                "$vinv": {
                  "unit": "Centimeter",
                  "unitSymbol": "cm"
                }
              }
            }
          }
        },
        "image_crown": {
          "title": "Image of the trunk",
          "description": "Image of the trunk",
          "$schema": "http://json-schema.org/draft-07/schema#",
          "type": [
            "object",
            "null"
          ],
          "required": [
            "uri"
          ],
          "properties": {
            "uri": {
              "title": "Image",
              "description": "A universal resource identifier (URI), according to RFC3986.",
              "type": "string",
              "format": "uri",
              "examples": [
                "https://schema.vinv.io/asset/img/logo.png"
              ]
            },
            "encoder": {
              "title": "Encoder",
              "description": "The encoder used to encode the image.",
              "type": [
                "string",
                "null"
              ],
              "default": "image/webp",
              "enum": [
                "image/jpeg",
                "image/webp"
              ],
              "examples": [
                "image/webp",
                "image/jpeg"
              ]
            },
            "compression": {
              "title": "Compression",
              "description": "The compression used to encode the image.",
              "type": [
                "number",
                "null"
              ],
              "minimum": 0,
              "maximum": 1,
              "default": 1,
              "examples": [
                0.8
              ]
            },
            "width": {
              "title": "Width",
              "description": "Width of the image.",
              "type": [
                "integer",
                "null"
              ],
              "minimum": 25,
              "maximum": 10000,
              "examples": [
                500
              ],
              "$vinv": {
                "unit": "Pixel",
                "unitSymbol": "px"
              }
            },
            "height": {
              "title": "Height",
              "description": "Height of the image",
              "type": [
                "integer",
                "null"
              ],
              "minimum": 25,
              "maximum": 10000,
              "examples": [
                500
              ],
              "$vinv": {
                "unit": "Pixel",
                "unitSymbol": "px"
              }
            }
          },
          "$vinv": {
            "id": "https://schema.vinv.io/image/en/0.0.1.json"
          }
        }
      }
    },
    "birth": {
      "title": "Birthday",
      "description": "Birthday of the tree",
      "type": [
        "string",
        "null"
      ],
      "format": "date",
      "examples": [
        "2010-09-13"
      ]
    },
    "treeNumber": {
      "title": "Unique number",
      "description": "Number/ID of the tree",
      "type": "string",
      "maxLength": 26,
      "examples": [
        "#1",
        "45",
        "ASDF435gHDFGhsgj5646"
      ]
    }
  }
}

=== vinv-group/vinv-schema/docs/tree/en/0.0.2-beta/example.json
{
  "species": "JM2",
  "trunk": {
    "dimensions": [
      {
        "height": 0.1,
        "diameter": 308
      },
      {
        "height": 0.1,
        "diameter": 308
      },
      {
        "height": 0.1,
        "diameter": 308
      }
    ],
    "image_trunk": {
      "uri": "https://schema.vinv.io/asset/img/logo.png",
      "encoder": "image/jpeg",
      "compression": 0.8,
      "width": 500,
      "height": 500
    }
  },
  "crown": {
    "dimensions": [
      {
        "height": 0.1,
        "diameter": 308
      },
      {
        "height": 0.1,
        "diameter": 308
      },
      {
        "height": 0.1,
        "diameter": 308
      }
    ],
    "image_crown": {
      "uri": "https://schema.vinv.io/asset/img/logo.png",
      "encoder": "image/jpeg",
      "compression": 0.8,
      "width": 500,
      "height": 500
    }
  },
  "birth": "2010-09-13",
  "treeNumber": "ASDF435gHDFGhsgj5646"
}
