=== vinv-group/vinv-schema/docs/tree/en/0.0.1.json
{
    "$id": "https://schema.vinv.io/vinv-individual-tree/0.0.1.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Individual Tree",
    "description": "Tree definition",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "species"
    ],
    "properties": {
        "species": {
            "$ref": "https://schema.vinv.io/species/0.0.1.json"
        },
        "trunk": {
            "type": ["object", "null"],
            "title": "Trunk",
            "description": "Trunk definition",
            "required": [
                "dimensions"
            ],
            "properties": {
                "dimensions": {
                    "title": "Dimensions",
                    "description": "Diameter per height",
                    "additionalProperties": false,
                    "type": "array",
                    "items": {"$ref": "https://schema.vinv.io/diameter_at_height/0.0.1.json"}
                },
                "image_trunk": { 
                    "title": "Image",
                    "description": "Image of the trunk",
                    "$ref": "https://schema.vinv.io/image/0.0.1.json"
                }
            }
        },
        "crown": {
            "type": ["object", "null"],
            "title": "Crown",
            "description": "Crown definition",
            "required": [
                "dimensions"
            ],
            "properties": {
                "dimensions": {
                    "title": "Dimensions",
                    "description": "Diameter per height",
                    "type": "array",
                    "items": {"$ref": "https://schema.vinv.io/diameter_at_height/0.0.1.json"}
                },
                "image_crown": { 
                    "title": "Image of the trunk",
                    "description": "Image of the trunk",
                    "$ref": "https://schema.vinv.io/image/0.0.1.json"
                }
            }
        },
        "birth": {
            "title": "Birthday",
            "description": "Birthday of the tree",
            "type": ["string", "null"],
            "format": "date",
            "examples": [
                "2010-09-13"
            ]
        },
        "treeNumber": {
            "title": "Unique number",
            "description": "Number/ID of the tree",
            "type": "string",
            "maxLength": 26,
            "examples": [
                "#1",
                "45",
                "ASDF435gHDFGhsgj5646"
            ]
        }
    }
}

=== vinv-group/vinv-schema/docs/tree/en/0.0.1/example.json
{
  "species": "JM2",
  "trunk": {
    "dimensions": [],
    "image_trunk": {
      "uri": "https://schema.vinv.io/asset/img/logo.png",
      "encoder": "image/jpeg",
      "compression": 0.8,
      "width": 500,
      "height": 500
    }
  },
  "crown": {
    "dimensions": [],
    "image_crown": {
      "uri": "https://schema.vinv.io/asset/img/logo.png",
      "encoder": "image/jpeg",
      "compression": 0.8,
      "width": 500,
      "height": 500
    }
  },
  "birth": "2010-09-13",
  "treeNumber": "ASDF435gHDFGhsgj5646",
  "$schema": "https://schema.vinv.io/vinv-individual-tree/0.0.1.json"
}
